apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator
    project: mss-boot
    version: v1
  name: generator
spec:
  selector:
    matchLabels:
      app: generator
      project: mss-boot
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: generator
        project: mss-boot
        version: v1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mssbootio/generator:4b5eed4c2090b820ab648a75d315ee6fa629277f
          name: generator
          ports:
            - containerPort: 8081
          resources: {}
          volumeMounts:
            - mountPath: /app/cfg
              name: mss-boot-generator-config
              readOnly: true
      volumes:
        - configMap:
            name: mss-boot-generator-config
          name: mss-boot-generator-config
