apiVersion: v1
kind: Service
metadata:
  labels:
    app: generator
    version: v1
  name: generator
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: generator
  type: ClusterIP
