apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
    version: v1
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: admin
        version: v1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mssbootio/admin:8ea478094ab2c05399131909a1dae7b3f05f250e
          name: admin
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts: []
      volumes: []
