apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oos-gateway
    project: mss-boot
    version: v1
  name: oos-gateway
spec:
  selector:
    matchLabels:
      app: oos-gateway
      project: mss-boot
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: oos-gateway
        project: mss-boot
        version: v1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mssbootio/oos-gateway:748c24696e5377bf6bc37e7985948b4c98c62d8e
          name: oos-gateway
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app/cfg
              name: mss-boot-oos-gateway-config
              readOnly: true
      volumes:
        - configMap:
            name: mss-boot-oos-gateway-config
          name: mss-boot-oos-gateway-config
