apiVersion: v1
kind: Service
metadata:
  labels:
    app: store
    project: mss-boot
    version: v1
  name: store
spec:
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
  selector:
    app: store
  type: ClusterIP
