apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
    project: mss-boot
    version: v1
  name: admin
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: admin
  type: ClusterIP
