apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
    version: v1
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: admin
        version: v1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mssbootio/admin:c505752b48817b8a98ab039fdae982be765b66c6
          name: admin
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app/cfg
              name: mss-boot-admin-config
              readOnly: true
      volumes:
        - configMap:
            name: mss-boot-admin-config
          name: mss-boot-admin-config
