apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s3-gateway
    project: mss-boot
    version: v1
  name: s3-gateway
spec:
  selector:
    matchLabels:
      app: s3-gateway
      project: mss-boot
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: s3-gateway
        project: mss-boot
        version: v1
    spec:
      containers:
        - env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: mssbootio/s3-gateway:a6f964ed1c78514152b1bb006a18f377b39a0ad4
          name: s3-gateway
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app/cfg
              name: mss-boot-s3-gateway-config
              readOnly: true
      volumes:
        - configMap:
            name: mss-boot-s3-gateway-config
          name: mss-boot-s3-gateway-config
