apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3-gateway
    project: mss-boot
    version: v1
  name: s3-gateway
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: s3-gateway
  type: ClusterIP
